### ISSUE TITLE
Column Header in view

### ISSUE THREAD

**Issue by rajibulhuda** [pascal-martinez/znetdk4mobile#5]
Hi Pascal,

Have a good day, I've searched through the docs and demos but can not find proper way to add column header for the view (e.g., ContactList grid view). I've checked the view in engine/core/view/users.php but can't understand it properly. 

Thanks

**Comment by pascal-martinez** [comment]
Hi Rajibul,

It can be a little difficult to style a list header because you need to consider displaying on large, medium, and small devices.
Below is a suggested code to insert before the [tutorial contact list](https://mobile.znetdk.fr/tutorial#z4m-tu-style).

````html
<header class="w3-row w3-padding w3-text-theme w3-theme-light w3-hide-small w3-border-bottom w3-border-theme" style="top:90px;position:sticky">
    <div class="w3-col" style="width: 60px">&nbsp;</div>
    <div class="w3-rest w3-row">
        <div class="w3-col l3 w3-padding-small w3-hide-medium"><b>Name</b></div>
        <div class="w3-col m5 w3-padding-small w3-hide-large"><b>Name</b></div>
        <div class="w3-col m4 l3 w3-padding-small"><b>Address</b></div>
        <div class="w3-col l4 w3-padding-small w3-hide-medium"><b>Email</b></div>
        <div class="w3-col m3 l2 w3-padding-small"><b>Phone</b></div>
    </div>
</header>
```` 
This code uses the W3CSS classes dedicated to responsive display: `w3-col`, `l[x]`, `m[x]`, `w3-hide-small`, `w3-hide-medium`, `w3-hide-large`. See documentation  at [https://www.w3schools.com/w3css/w3css_responsive.asp](https://www.w3schools.com/w3css/w3css_responsive.asp).

Regards,
Pascal

**Comment by rajibulhuda** [comment]
Hi Pascal, 
Somehow it's working perfectly! Thank you very much. 

Best Regards 
Rajibul
